steps:
  # Build and push image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/poke-math/poke-math:latest',
      '--build-arg', 'ENVIRONMENT=${_ENV}',
      '.'
    ]
    id: 'build'

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/poke-math/poke-math:latest'
    ]
    id: 'push'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy poke-math \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/poke-math/poke-math:latest \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated

# Add options for logging
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west1
  _ENV: prod
