steps:
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/poke-math/poke-math:$COMMIT_SHA
      - --build-arg
      - COMMIT_SHA=$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/docker
    id: push
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/poke-math/poke-math:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: deploy-private
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - poke-math
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/poke-math/poke-math:$COMMIT_SHA
      - --region=${_REGION}
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: europe-west1
