"""Throwaway local-only UI prototype for equation calibration.

Run with: uv run python tools/equation_calibration_prototype.py
Open: http://127.0.0.1:8091/?variant=A (or B / C)

Question/plan: Test three layouts for showing every capability level for one seed, with a plain-language capability beside each representative exercise, without crowding the progression.
"""

import os

from flask import Flask, render_template_string


app = Flask(__name__)

# This is a deliberately separate, local-only tool. Set to "production" to hide the evaluator switcher.
SHOW_SWITCHER = os.environ.get("EQUATION_CALIBRATION_PROTOTYPE_ENV", "local") != "production"

# Representative prototype data only: this is not generator output or calibrated production content.
LEVELS = [
    {"id": "L1", "order": 1, "name": "One operation", "capability": "Evaluate one arithmetic operation on positive integers.", "exercise": "8 + 7 = ?", "answer": "15", "properties": ["addition", "0 variables", "integer answer"]},
    {"id": "L2", "order": 2, "name": "Order of operations", "capability": "Evaluate composed arithmetic using operation order and exact division.", "exercise": "18 ÷ 3 + 4 × 2 = ?", "answer": "14", "properties": ["mixed operations", "0 variables", "exact division"]},
    {"id": "L3", "order": 3, "name": "Missing value", "capability": "Find a missing value and verify equality when the unknown appears in a different position.", "exercise": "15 = y + 7", "answer": "y = 8", "properties": ["equality", "1 variable", "unknown on right"]},
    {"id": "L4", "order": 4, "name": "Evaluate an expression", "capability": "Substitute a supplied value for x and evaluate a variable expression with simple distribution.", "exercise": "x = 4; 3(x + 2) = ?", "answer": "18", "properties": ["substitution", "1 variable", "distribution"]},
    {"id": "L5", "order": 5, "name": "One-step equation", "capability": "Solve and verify a one-step equation with an integer solution.", "exercise": "x − 9 = 17", "answer": "x = 26", "properties": ["linear", "1 variable", "one inverse step"]},
    {"id": "L6", "order": 6, "name": "Two-step equation", "capability": "Solve a two-step equation, including a negative coefficient or solution.", "exercise": "−3x + 4 = 19", "answer": "x = −5", "properties": ["linear", "1 variable", "negative solution"]},
    {"id": "L7", "order": 7, "name": "Simplify, then solve", "capability": "Distribute and collect like terms before solving a linear equation.", "exercise": "2(x + 3) + x = 21", "answer": "x = 5", "properties": ["linear", "1 variable", "distribute + collect"]},
    {"id": "L8", "order": 8, "name": "Variables on both sides", "capability": "Solve a linear equation with variable terms on both sides and a unique solution.", "exercise": "5x − 4 = 2x + 11", "answer": "x = 5", "properties": ["linear", "1 variable", "unique solution"]},
    {"id": "L9", "order": 9, "name": "Two clues together", "capability": "Solve a uniquely solvable 2×2 linear system for x and y.", "exercise": "2x + y = 17\nx − y = 1", "answer": "x = 6, y = 5", "properties": ["linear system", "2 variables", "unique solution"]},
]

PAGE = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Equation calibration — throwaway prototype</title>
  <style>
    :root { --red:#ff1f1f; --blue:#1f1fff; --yellow:#ffd733; --ink:#252525; --muted:#666; --paper:#fff; --canvas:#fafafa; --line:#dedede; --green:#4caf50; font-family:Arial Rounded MT Bold, Arial, sans-serif; color:var(--ink); background:var(--canvas); }
    * { box-sizing:border-box; } body { margin:0; padding:0 0 5.5rem; } .topbar { background:var(--red); color:#fff; padding:1.25rem clamp(1rem,4vw,4rem); box-shadow:0 2px 5px #0002; } .topbar-inner { max-width:1200px; margin:auto; } .eyebrow { font-size:.72rem; font-weight:800; letter-spacing:.08em; text-transform:uppercase; opacity:.92; } h1 { font-size:clamp(1.65rem,4vw,2.5rem); margin:.25rem 0; text-shadow:2px 2px 4px #0003; } .topbar p { max-width:52rem; margin:.35rem 0 0; line-height:1.45; } main { max-width:1200px; margin:auto; padding:clamp(1rem,3vw,2rem); } .notice { border:2px dashed var(--blue); background:#eef0ff; border-radius:12px; padding:.75rem 1rem; margin-bottom:1.2rem; font-size:.9rem; } .notice strong { color:var(--blue); } h2 { margin:0; font-size:clamp(1.3rem,3vw,1.8rem); } .lede { color:var(--muted); margin:.4rem 0 1.25rem; line-height:1.45; } .meta { display:flex; flex-wrap:wrap; gap:.45rem; margin:.65rem 0 1rem; } .pill { display:inline-block; background:#f0f0f0; border:1px solid var(--line); border-radius:99px; padding:.28rem .6rem; font-size:.75rem; } .seed { background:var(--yellow); border-color:#e1b900; font-weight:bold; }
    .level-card, .table-wrap, .band, .focus-card, .rail { background:var(--paper); border-radius:15px; box-shadow:0 2px 6px #0002; } .level-card { display:grid; grid-template-columns:minmax(155px,.7fr) minmax(220px,1.15fr) minmax(140px,.7fr); gap:1rem; padding:1rem; position:relative; } .level-card + .level-card { margin-top:.8rem; } .level-card::before { content:""; position:absolute; left:1.25rem; top:-.8rem; height:.8rem; border-left:3px solid var(--blue); } .level-card:first-of-type::before { display:none; } .number { color:var(--blue); font-size:.78rem; font-weight:800; letter-spacing:.07em; } .level-card h3, .rail h3, .band h3, .focus-card h3 { margin:.18rem 0 .35rem; font-size:1rem; } .capability { line-height:1.45; margin:0; } .exercise { font:600 1.2rem/1.45 ui-monospace, SFMono-Regular, Consolas, monospace; white-space:pre-line; background:#f7f7f7; border-left:4px solid var(--red); padding:.65rem .8rem; border-radius:5px; margin:0; } .answer { color:#176a2b; font-weight:bold; margin:.65rem 0 0; } .answer span { color:var(--muted); font-weight:normal; }
    .table-wrap { overflow-x:auto; } table { border-collapse:collapse; width:100%; min-width:740px; text-align:left; } th { background:#242424; color:white; font-size:.78rem; letter-spacing:.04em; text-transform:uppercase; padding:.8rem; } td { padding:.85rem; vertical-align:top; border-bottom:1px solid var(--line); line-height:1.4; } tr:last-child td { border-bottom:0; } .table-level { white-space:nowrap; color:var(--blue); font-weight:bold; } .table-exercise { font-family:ui-monospace, SFMono-Regular, Consolas, monospace; white-space:pre-line; } .small-answer { color:#176a2b; font-weight:bold; } .property-list { display:flex; flex-wrap:wrap; gap:.3rem; } .property-list .pill { font-size:.68rem; padding:.18rem .4rem; }
    .calibration-layout { display:grid; grid-template-columns:235px 1fr; gap:1rem; align-items:start; } .rail { position:sticky; top:1rem; padding:.85rem; } .rail-intro { color:var(--muted); font-size:.82rem; line-height:1.35; margin:.15rem 0 .6rem; } .rail-item { display:flex; gap:.55rem; padding:.48rem; border-bottom:1px solid #eee; font-size:.8rem; } .rail-item:last-child { border:0; } .rail-order { color:var(--blue); font-weight:bold; } .bands { display:grid; gap:1rem; } .band { padding:1rem; border-top:5px solid var(--blue); } .band:nth-child(2) { border-top-color:var(--yellow); } .band:nth-child(3) { border-top-color:var(--red); } .band-header { display:flex; justify-content:space-between; gap:.75rem; align-items:baseline; margin-bottom:.75rem; } .band-header p { margin:0; color:var(--muted); font-size:.85rem; } .mini-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:.7rem; } .mini { border:1px solid var(--line); border-radius:9px; padding:.75rem; } .mini .capability { font-size:.83rem; } .mini .exercise { font-size:.95rem; margin-top:.55rem; } .focus-card { padding:1rem; border:2px solid var(--red); } .focus-label { color:var(--red); text-transform:uppercase; letter-spacing:.07em; font-size:.72rem; font-weight:bold; }
    .prototype-switcher { position:fixed; z-index:10; bottom:1rem; left:50%; transform:translateX(-50%); display:flex; align-items:center; gap:.5rem; padding:.45rem .55rem; border:2px solid var(--yellow); border-radius:999px; background:#171717; color:white; box-shadow:0 5px 18px #0005; } .prototype-switcher button { cursor:pointer; background:var(--yellow); color:#222; border:0; border-radius:999px; width:2.15rem; height:2.15rem; font-size:1.3rem; font-weight:bold; } .prototype-switcher button:hover { background:white; } .switch-copy { min-width:156px; text-align:center; font-size:.76rem; line-height:1.25; } .switch-copy strong { display:block; color:var(--yellow); } .state { margin-top:1.5rem; color:var(--muted); font-size:.78rem; text-align:center; }
    @media (max-width:720px) { .level-card { grid-template-columns:1fr; gap:.55rem; } .level-card::before { display:none; } .calibration-layout { grid-template-columns:1fr; } .rail { position:static; } .rail-levels { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); } .rail-item { border:1px solid #eee; } .mini-grid { grid-template-columns:1fr; } .prototype-switcher { width:calc(100% - 1.2rem); justify-content:center; } }
  </style>
</head>
<body>
  <header class="topbar"><div class="topbar-inner"><div class="eyebrow">Local-only · throwaway design prototype</div><h1>Equation calibration for seed “Caterpie”</h1><p>Can one screen expose the complete capability progression, while keeping the human explanation beside the exercise that represents it?</p></div></header>
  <main>
    <div class="notice"><strong>Representative/prototype data.</strong> These hard-coded exercises are only for evaluating layout density; they are not generator output, calibrated thresholds, or player-facing copy.</div>
    <div class="meta"><span class="pill seed">Seed: Caterpie #010</span><span class="pill">9 capability levels</span><span class="pill">Start: one operation</span><span class="pill">End: unique 2×2 system</span></div>
    <section id="variant-a" hidden><h2>A — Progression journey</h2><p class="lede">A spacious, linear reading path: each stop couples the capability statement with its concrete evidence.</p>{% for level in levels %}<article class="level-card"><div><div class="number">{{ level.id }} · LEVEL {{ level.order }}</div><h3>{{ level.name }}</h3><div class="property-list">{% for item in level.properties %}<span class="pill">{{ item }}</span>{% endfor %}</div></div><div><div class="eyebrow" style="color:#666">Capability</div><p class="capability">{{ level.capability }}</p></div><div><div class="eyebrow" style="color:#666">Representative exercise</div><p class="exercise">{{ level.exercise }}</p><p class="answer"><span>Answer:</span> {{ level.answer }}</p></div></article>{% endfor %}</section>
    <section id="variant-b" hidden><h2>B — Calibration scan sheet</h2><p class="lede">A dense comparison view for quickly checking the whole sequence, properties, and jumps in complexity.</p><div class="table-wrap"><table><thead><tr><th>Level</th><th>Capability description</th><th>Representative exercise</th><th>Answer</th><th>Measured properties</th></tr></thead><tbody>{% for level in levels %}<tr><td class="table-level">{{ level.id }}<br><span style="color:#333;font-weight:normal">{{ level.name }}</span></td><td>{{ level.capability }}</td><td class="table-exercise">{{ level.exercise }}</td><td class="small-answer">{{ level.answer }}</td><td><div class="property-list">{% for item in level.properties %}<span class="pill">{{ item }}</span>{% endfor %}</div></td></tr>{% endfor %}</tbody></table></div></section>
    <section id="variant-c" hidden><h2>C — Calibration bands + endpoint focus</h2><p class="lede">A persistent overview rail makes every level visible; grouped bands emphasize the transitions, with the final target shown at full detail.</p><div class="calibration-layout"><aside class="rail"><h3>Full progression</h3><p class="rail-intro">Every level stays in view while the right side groups the same progression into capability bands.</p><div class="rail-levels">{% for level in levels %}<div class="rail-item"><span class="rail-order">{{ level.order }}</span><span><strong>{{ level.id }}</strong><br>{{ level.name }}</span></div>{% endfor %}</div></aside><div class="bands"><section class="band"><div class="band-header"><h3>1. Compute</h3><p>Levels L1–L2</p></div><div class="mini-grid">{% for level in levels[:2] %}<article class="mini"><div class="number">{{ level.id }} · {{ level.name }}</div><p class="capability">{{ level.capability }}</p><p class="exercise">{{ level.exercise }}</p><p class="answer"><span>Answer:</span> {{ level.answer }}</p></article>{% endfor %}</div></section><section class="band"><div class="band-header"><h3>2. Relate and evaluate</h3><p>Levels L3–L4</p></div><div class="mini-grid">{% for level in levels[2:4] %}<article class="mini"><div class="number">{{ level.id }} · {{ level.name }}</div><p class="capability">{{ level.capability }}</p><p class="exercise">{{ level.exercise }}</p><p class="answer"><span>Answer:</span> {{ level.answer }}</p></article>{% endfor %}</div></section><section class="band"><div class="band-header"><h3>3. Solve one variable</h3><p>Levels L5–L8</p></div><div class="mini-grid">{% for level in levels[4:8] %}<article class="mini"><div class="number">{{ level.id }} · {{ level.name }}</div><p class="capability">{{ level.capability }}</p><p class="exercise">{{ level.exercise }}</p><p class="answer"><span>Answer:</span> {{ level.answer }}</p></article>{% endfor %}</div></section><section class="focus-card"><div class="focus-label">Progression endpoint · L9</div><h3>{{ levels[8].name }}</h3><p class="capability">{{ levels[8].capability }}</p><p class="exercise">{{ levels[8].exercise }}</p><p class="answer"><span>Answer:</span> {{ levels[8].answer }}</p><div class="property-list">{% for item in levels[8].properties %}<span class="pill">{{ item }}</span>{% endfor %}</div></section></div></div></section>
    <p class="state" id="prototype-state" aria-live="polite"></p>
  </main>
  {% if show_switcher %}<nav class="prototype-switcher" aria-label="Local prototype variant switcher"><button type="button" id="previous" aria-label="Previous variant">←</button><div class="switch-copy"><strong>LOCAL PROTOTYPE CONTROL</strong><span id="variant-label"></span></div><button type="button" id="next" aria-label="Next variant">→</button></nav>{% endif %}
  <script>
    const variants = { A: 'Progression journey', B: 'Calibration scan sheet', C: 'Calibration bands + endpoint focus' };
    const keys = Object.keys(variants); const params = new URLSearchParams(window.location.search); let current = params.get('variant'); if (!variants[current]) current = 'A';
    function renderVariant() { keys.forEach(key => document.getElementById('variant-' + key.toLowerCase()).hidden = key !== current); const label = document.getElementById('variant-label'); if (label) label.textContent = current + ' — ' + variants[current]; document.getElementById('prototype-state').textContent = 'Visible prototype state: variant ' + current + ' (' + variants[current] + '); all 9 representative levels are rendered.'; }
    function move(direction) { current = keys[(keys.indexOf(current) + direction + keys.length) % keys.length]; const next = new URL(window.location.href); next.searchParams.set('variant', current); window.history.replaceState({}, '', next); renderVariant(); }
    document.getElementById('previous')?.addEventListener('click', () => move(-1)); document.getElementById('next')?.addEventListener('click', () => move(1));
    window.addEventListener('keydown', event => { const target = event.target; if (target.matches?.('input, textarea, [contenteditable]') || target.isContentEditable) return; if (event.key === 'ArrowLeft') move(-1); if (event.key === 'ArrowRight') move(1); }); renderVariant();
  </script>
</body></html>'''


@app.get("/")
def calibration_prototype():
    """Render the throwaway calibration comparison surface."""
    return render_template_string(PAGE, levels=LEVELS, show_switcher=SHOW_SWITCHER)


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8091, debug=True)
