# CI definition for IaC (terraform)
steps:
  # Create tfvars file from secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "project_id = \"$PROJECT_ID\"" > terraform.tfvars
        echo "project_number = \"$(gcloud projects describe $PROJECT_ID --format='value(projectNumber)')\"" >> terraform.tfvars
        echo "tfstate_bucket = \"tfstate-$PROJECT_ID-${_REGION}-${_ENV}\"" >> terraform.tfvars

  - name: hashicorp/terraform:1.5
    entrypoint: sh
    args:
      - -c
      - |
        terraform init
        terraform validate
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan

substitutions:
  _REGION: europe-west1
  _ENV: prod
